name: Docker Slim

on:
  push:
    branches: [ "main" ]

jobs:
  setupandrun:
    name: Setup and run
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Update system repos
      run: sudo apt-get update && sudo apt-get upgrade
      
    - name: Download and setup
      run: curl -sL https://raw.githubusercontent.com/docker-slim/docker-slim/master/scripts/install-dockerslim.sh | sudo -E bash -
      
    - name: Build Docker container
      run: ls && docker build -t akhaneducation/my-first-image .
      
    - name: Build and optimise
      run: docker images && docker-slim --debug build akhaneducation/my-first-image --show-clogs
